### ISSUE TITLE
Can I just compare two matrices 

### ISSUE THREAD

**Issue by mytarmail** [vwmaus/twdtw#4]
Can I just compare two matrices where each row is an observation and the matrices have different number of rows?

m1 <- matrix(rnorm(30),ncol = 2)
m2 <- matrix(rnorm(50),ncol = 2)

library(twdtw)
twdtw(m1, m2)

**Comment by vwmaus** [comment]
A differing number of observations (rows) between matrices is acceptable. However, the first column of both matrices should serve as a time reference for the observations. Moreover, when using the `twdtw` function, the arguments `cycle_length`, `time_scale`, and `time_weight` are required. For more details, refer to `?twdtw`.
